version: 2
updates:
  - package-ecosystem: npm
    directory: "/packages/@dcl/sdk"
    schedule:
      interval: daily
    allow:
      - dependency-name: "@dcl/kernel"
      - dependency-name: "@dcl/schemas"
      - dependency-name: "@dcl/unity-renderer"
    versioning-strategy: auto
