version: 2
updates:
  - package-ecosystem: npm
    directory: "/packages/decentraland-ecs"
    schedule:
      interval: daily
    allow:
      - dependency-name: "@dcl/explorer"
      - dependency-name: "@dcl/posix"
      - dependency-name: "@dcl/schemas"
    versioning-strategy: auto

  - package-ecosystem: npm
    directory: "/packages/@dcl/legacy-ecs"
    schedule:
      interval: daily
    allow:
      - dependency-name: "@dcl/*"
    versioning-strategy: increase
