import { writeFile } from 'fs/promises'
import path, { resolve } from 'path'
import { itExecutes } from '../../scripts/helpers'

test('write a case-sensitive file to a destination folder', async () => {
  await writeFile(
    resolve(__dirname, './fixtures/ecs7-scene/aCaseSensitiveReadme.md'),
    'this autogenerated case sensitive filename will help debug issues with normalized filenames'
  )
})

describe('workspace: build a workspace using the CLI', () => {
  const cwd = resolve(__dirname, './fixtures')

  itExecutes(
    path.resolve(process.cwd(), './packages/@dcl/sdk-commands/dist/index.js') + ' build --customEntryPoint',
    cwd
  )
})

describe('workspace: export-static a workspace using the CLI', () => {
  const cwd = resolve(__dirname, './fixtures')

  itExecutes(
    path.resolve(process.cwd(), './packages/@dcl/sdk-commands/dist/index.js') +
      ' export-static --destination tmp/ipfs --realmName testRealm --baseUrl https://hola.com',
    cwd
  )
})
