import { PreEngine } from '../engine'

import { defineLibraryComponents } from './generated/index.gen'
import { ColliderLayer } from './generated/pb/decentraland/sdk/components/mesh_collider.gen'
import { defineTransformComponent } from './legacy/Transform'

import * as AnimatorSchema from './generated/Animator.gen'
import { defineAnimatorComponent } from './extended/Animator'

export enum COMPONENT_ID {
  SYNC = 1000
}

/**
 * @public
 */
export type SdkComponents = ReturnType<typeof defineSdkComponents>

export function defineSdkComponents(engine: PreEngine) {
  const autogeneratedComponents = defineLibraryComponents(engine)
  return {
    ...autogeneratedComponents,
    Animator: defineAnimatorComponent(engine),
    Transform: defineTransformComponent(engine)
  }
}
