import { IEngine } from '../engine'
import { defineLibraryComponents } from './generated/index.gen'
import { defineTransformComponent } from './legacy/Transform'
import { defineAnimatorComponent } from './extended/Animator'
import { defineMeshColliderComponent } from './extended/MeshCollider'
import { defineMeshRendererComponent } from './extended/MeshRenderer'
import { defineMaterialComponent } from './extended/Material'

export function defineSdkComponents(
  engine: Pick<IEngine, 'defineComponentFromSchema' | 'getComponent'>
) {
  const autogeneratedComponents = defineLibraryComponents(engine)
  return {
    ...autogeneratedComponents,
    Material: defineMaterialComponent(engine),
    Animator: defineAnimatorComponent(engine),
    MeshRenderer: defineMeshRendererComponent(engine),
    MeshCollider: defineMeshColliderComponent(engine),
    Transform: defineTransformComponent(engine)
  }
}
