name: Lint
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/@dcl/inspector/**'
      - 'packages/@dcl/creator-hub/**.js'
      - 'packages/@dcl/creator-hub/**.mjs'
      - 'packages/@dcl/creator-hub/**.cjs'
      - 'packages/@dcl/creator-hub/**.jsx'
      - 'packages/@dcl/creator-hub/**.ts'
      - 'packages/@dcl/creator-hub/**.mts'
      - 'packages/@dcl/creator-hub/**.cts'
      - 'packages/@dcl/creator-hub/**.tsx'
      - 'packages/@dcl/creator-hub/**.json'
  pull_request:
    paths:
      - 'packages/@dcl/inspector/**'
      - 'packages/@dcl/creator-hub/**.js'
      - 'packages/@dcl/creator-hub/**.mjs'
      - 'packages/@dcl/creator-hub/**.cjs'
      - 'packages/@dcl/creator-hub/**.jsx'
      - 'packages/@dcl/creator-hub/**.ts'
      - 'packages/@dcl/creator-hub/**.mts'
      - 'packages/@dcl/creator-hub/**.cts'
      - 'packages/@dcl/creator-hub/**.tsx'
      - 'packages/@dcl/creator-hub/**.json'

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'
    working-directory: packages/@dcl/creator-hub

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: packages/@dcl/creator-hub/package-lock.json

      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: npm run lint --if-present

  # This job just check code style for in-template contributions.
  code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: packages/@dcl/creator-hub/package-lock.json

      - run: npm i prettier
      - run: npx prettier --check "**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx,vue}"
